<?php


define( 'siteurl', 'https://www.codexfive.net/') ; 

/*
 *  siteurl is used for generating links in emails.  
 *  
 *  The addresses below are used as the 'from' field in autogenerated emails.
 *  
 */

$address["reg"] = "Site Registration <do-not-reply@codexfive.net>" ;

$subject['reg'] = 'Activate your Membership' ;






$message["reg"] = "A user at ".$_SERVER['REMOTE_ADDR']." has registered an account with our website.  If this was not you,
take no action, and the request will expire after 48 hours.  To activate your membership, click the
link below or copy and paste it into your web browser.

        ".siteurl."register/activate/%%USERID%%/%%KEY%%" ;



$address["reset"] = "Password Reset <do-not-reply@codexfive.net>" ;

$subject["reset"] = "Reset Your Password" ;

$message["reset"] = "A user at ".$_SERVER['REMOTE_ADDR']." has requested a password reset.  If this was not you,
take no action, and the request will expire after 24 hours.  To reset your password, click the
link below or copy and paste it into your web browser.

        ".siteurl."login/passwordreset/%%USERID%%/%%KEY%%" ;